language: c
compiler:
  - clang
  - gcc
before_install:
  - git submodule update --init --recursive
  - sudo apt-get install libperl-dev python3-dev ruby-dev liblua5.1-0-dev lua5.1
script: ./ci_run.sh
